services:
  ##############################################################################
  # ALGOPLATFORM
  ##############################################################################
  algoplatform_db:
    image: postgres:15
    container_name: algoplatform_db
    ports:
      - "5433:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - algoplatform_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    image: migrate/migrate:v4.15.2
    container_name: algoplatform_migrate
    restart: on-failure
    command: >
      -path=/migrations -database=postgres://${DB_USER}:${DB_PASSWORD}@algoplatform_db:5432/${DB_NAME}?sslmode=disable up
    volumes:
      - ./migrations:/migrations
    depends_on:
      algoplatform_db:
        condition: service_healthy
    networks:
      - app-network

  algoplatform:
    build: .
    container_name: algoplatform
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: on-failure
    depends_on:
      algoplatform_db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - app-network

##############################################################################
# VOLUMES AND NETWORK
##############################################################################
volumes:
  algoplatform_pgdata:

networks:
  app-network:
    driver: bridge
